### ISSUE TITLE
About Views

### ISSUE THREAD

**Issue by tmendesilva** [toluaina/pgsync#103]
Can I make schema.json using a VIEW as "table", or there some schema generator to make this JSON analyzing tables used on my VIEW query?

**Comment by toluaina** [comment]
Views are currently not supported yet. Some work has been done but its still WIP.

**Comment by tmendesilva** [comment]
Congrats for your job, i'm using to replace materialized views. I will try simulate views on schema, tnks.

**Comment by toluaina** [comment]
Thanks I will look at this shortly. Don't have an ETA yet sorry.

**Comment by yangyaofei** [comment]
@toluaina  hi, are you still working with this? I have a table with tree-like struct and I want get a path for every item for searching. Since there is no such method for recursive retrieving I create a recursive view to achieve that. 

But , I found view cannot be synced when change the data. 

Can you tell me how to make view work? I can implement it if I can.

**Comment by yangyaofei** [comment]
@toluaina yes, i have try it a little, as far as I upderstand because of there is no such thing like permarary key, so they cannot make the trigger run.

In My case, I create a trigger to make that view as a real table. 

Thank you for your reply.

**Comment by toluaina** [comment]
Sorry for the long wait. Support for views is detailed [here](https://github.com/toluaina/pgsync/issues/275)

**Comment by toluaina** [comment]
view are finally supported.
