### ISSUE TITLE
Children records ignored when a custom `foreign_key` key uses columns that aren't the primary key or an actual foreign key

### ISSUE THREAD

**Issue by fdeschenes** [toluaina/pgsync#114]
PGSync version: master

Postgres version: 9.6.19

Elasticsearch version: 7.12.0

Redis version: 5.0.12

Python version: 3.7.10

Problem Description: 

We can manually define foreign keys `foreign_key` in the schema and that while that works beautifully for the initial sync the triggers use the `_fkey_view` materialized view which only includes actual foreign keys defined in the table. We personally do not use actual foreign keys due to performance reasons.

What happens is that inserts in the children tables after the initial sync are completely ignored because the necessary column names/value pairs aren't included by the trigger.

Error Message (if any): 

```
Exception in thread Thread-71:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 793, in poll_redis
    self.on_publish(payloads)
  File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 866, in on_publish
    self.sync_payloads(_payload)
  File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 756, in sync_payloads
    payloads,
  File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 389, in _payloads
    value = payload_data[key]
KeyError: 'asset_id'
```

Potential Solution:

Instead of using a materialized view, I would suggest you use a table and insert the result of the query you use to create the materialized view _and_ all of the custom foreign keys defined in the schema. I manually did that and that fixed my problem.

**Comment by toluaina** [comment]
I have seen this something like this before. I think we can still move forward with the materialized view. 
The foreign keys defined in the schema are now included in the view columns.

**Comment by fdeschenes** [comment]
@toluaina Thank you! However, it looks like we recreate the materialized view with each index defined in the schema file so only the last one is persisted.

For example, the `_fkey_view` will only contain the foreign keys defined in the last definition (`index2`/`table2` and its children) if my `schema.json` looks something something like this:

```
[{
    "database": "database",
    "index": "index1",
    "nodes": [{
      "table": "table1"
      ...
    }]
},{
    "database": "database",
    "index": "index2",
    "nodes": [{
      "table": "table2"
      ...
    }]
}]
```

Thoughts?

**Comment by fdeschenes** [comment]
@toluaina That last one is almost perfect, thank you! The only thing now is that the `foreign_keys` column includes columns from the parent too and those columns don't necessarily exist in the children tables.

**Comment by toluaina** [comment]
Thanks for your analysis @fdeschenes .

So I am aware of this and I have added some comments in the code so to try to explain the reasoning behind this. 
Hopefully one day I can have tests that undeepin these behaviour.

- So a foreign key between two tables can be either in the parent or the child
- The schema (when using the foreign_keys property in a relationship) does not indicate the direction.
- This is because we want to keep things simple and not have the user worry about this.
- So the foreign_key can be in the parent or the child.
- In the [book](https://github.com/toluaina/pgsync/blob/master/examples/book/schema.py#L127-L148) example, when looking at the book and publisher table. The foreign key will be **_publisher_id_** and **_id_**
- It could also have been **_book_id_** and **_id_** and the one that is foreign will depend. (assuiming we have book_id in the publisher table)
- Depending on the schema structure, the publisher can also be our document root - meaning that parent and child are inverted. 
- I feel this does not matter anyway becaue the only reasion we have these foreign_keys and primary_keys view tables is so that we don't have to pass the entire row payload to pg_notify
- This is becaue of the payload data limit for pg_notify. 
- We use the payload data [here](https://github.com/toluaina/pgsync/blob/1.1.32/pgsync/sync.py#L389) to build the resulting query so it does not matter becaue we are using the foreign_keys for the table sitself anyway. 

Hope this is a little clear.

**Comment by toluaina** [comment]
This has been published. Closing this, thanks
